-- liquibase formatted sql

-- changeset mariyatarasenko:1
create table if not exists customer
(
    id bigint generated by default as identity
        primary key,
    chat_id     bigint not null,
    surname     text,
    name        text,
    second_name text,
    phone       text,
    address     text
);

create table if not exists shelter
(
    id  bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    address      text,
    location_map text,
    name         text
);

create table if not exists volunteer
(
    id  bigint generated by default as identity
        primary key,
    address     text,
    chat_id     bigint not null,
    name        text,
    phone       text,
    second_name text,
    surname     text
);

create table if not exists info
(
    id  bigint generated by default as identity
        primary key,
    area         text,
    instructions text
);

create table if not exists breed
(
    id  bigint generated by default as identity
        primary key,
    adult_pet_from_age    integer not null,
    breed                 text,
    recommendations_adult text,
    recommendations_child text
);

create table if not exists pet
(
    id  bigint generated by default as identity
        primary key,
    age_in_months integer not null,
    decision_date timestamp,
    file_path     varchar(255),
    file_size     bigint,
    media_type    varchar(255),
    name          text,
    photo         bytea,
    id_customer   bigint,
    id_shelter    bigint,
    id_breed      bigint
);

create table if not exists report
(
    id  bigint generated by default as identity
        primary key,
    date       timestamp,
    file_path  varchar(255),
    file_size  bigint,
    media_type varchar(255),
    pet_report varchar(255),
    photo      bytea,
    id_pet     bigint
);
